# NumPy Array Concatenation & Split

# Concatenation 

In [1]:
from numpy import*

In [2]:
arr1 = arange(1,17).reshape(4,4)
arr2 = arange(17,33).reshape(4,4)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [3]:
concatenate((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [4]:
concatenate((arr1, arr2, arr1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
stack((arr1, arr2), axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [6]:
stack((arr1, arr2), axis = 1)

array([[[ 1,  2,  3,  4],
        [17, 18, 19, 20]],

       [[ 5,  6,  7,  8],
        [21, 22, 23, 24]],

       [[ 9, 10, 11, 12],
        [25, 26, 27, 28]],

       [[13, 14, 15, 16],
        [29, 30, 31, 32]]])

In [7]:
vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
hstack((arr1, arr1, arr2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8,  5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12,  9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 13, 14, 15, 16, 29, 30, 31, 32]])

In [9]:
concatenate((arr1, arr2), axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
concatenate((arr1, arr2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [11]:
dstack((arr1, arr2))

array([[[ 1, 17],
        [ 2, 18],
        [ 3, 19],
        [ 4, 20]],

       [[ 5, 21],
        [ 6, 22],
        [ 7, 23],
        [ 8, 24]],

       [[ 9, 25],
        [10, 26],
        [11, 27],
        [12, 28]],

       [[13, 29],
        [14, 30],
        [15, 31],
        [16, 32]]])

# Splitting

# split() 

In [17]:
A = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
split(A, 2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [21]:
# Using index for print different size of array
split(A, [2,4,5,8])

[array([1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([ 9, 10])]

# array_split() 

In [22]:
array_split(A, 3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [25]:
array_split(A, 4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]

# horizontal split()

In [26]:
hsplit(A, 2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [28]:
hsplit(A, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

# vertical split() 

In [43]:
B = arange(1,7).reshape(2,3)
print(B)

[[1 2 3]
 [4 5 6]]


In [44]:
vsplit(B, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [42]:
vsplit(B, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]