# Mathematic Operation Using NumPy 

In [1]:
from numpy import *

In [3]:
arr1 = arange(1,10).reshape(3,3)
arr2 = arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Addition 

In [6]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Subtraction 

In [8]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Multiplication

In [13]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# Product

In [15]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Division 

In [10]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Find Maximum Value

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr1.max()

9

# Find maximum index Value

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr1.argmax()

8

# Find maximum value in column

In [22]:
arr1.max(axis = 0)

array([7, 8, 9])

# Find maximum value in row

In [24]:
arr1.max(axis = 1)

array([3, 6, 9])

# Find minimum  value

In [25]:
arr1.min()

1

# Find minimum index value

In [27]:
arr1.argmin()

0

# Find minimum value in column

In [28]:
arr1.min(axis = 0)

array([1, 2, 3])

# Find minimum value in row

In [29]:
arr1.min(axis = 1)

array([1, 4, 7])

# Sum array all element 

In [30]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
sum(arr1)

45

# Sum array column element

In [34]:
sum(arr1, axis = 0)

array([12, 15, 18])

# Sum array row element

In [35]:
sum(arr1, axis = 1)

array([ 6, 15, 24])

# Find average of an array 

In [ ]:
# mean = sum of all outcomes / total no. of outcome
mean(arr1)

# Find square root of an array

In [38]:
sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# standard division 

In [39]:
std(arr1)

2.581988897471611

# exponent

In [40]:
exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# log 

In [41]:
log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [42]:
log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [43]:
log2(arr1)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])