# NumPy Functions:

In [1]:
from numpy import *

# linspace() 

In [2]:
a =  linspace(1, 10, 5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [3]:
a =  linspace(1, 10, 5, endpoint = False)
print(a)

[1.  2.8 4.6 6.4 8.2]


# arange() 

In [4]:
a = arange(1,6)
print(a)

[1 2 3 4 5]


In [5]:
# Print Even No.
a =arange(2,13,2)
print("The even no. is :",a)

#Print Odd No.
a = arange(1,13,2)
print("The odd no. is :",a)

The even no. is : [ 2  4  6  8 10 12]
The odd no. is : [ 1  3  5  7  9 11]


# logspace()

In [6]:
a = logspace(1,3,5)
print(a)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [7]:
a = logspace(1,5)
print(a)

[1.00000000e+01 1.20679264e+01 1.45634848e+01 1.75751062e+01
 2.12095089e+01 2.55954792e+01 3.08884360e+01 3.72759372e+01
 4.49843267e+01 5.42867544e+01 6.55128557e+01 7.90604321e+01
 9.54095476e+01 1.15139540e+02 1.38949549e+02 1.67683294e+02
 2.02358965e+02 2.44205309e+02 2.94705170e+02 3.55648031e+02
 4.29193426e+02 5.17947468e+02 6.25055193e+02 7.54312006e+02
 9.10298178e+02 1.09854114e+03 1.32571137e+03 1.59985872e+03
 1.93069773e+03 2.32995181e+03 2.81176870e+03 3.39322177e+03
 4.09491506e+03 4.94171336e+03 5.96362332e+03 7.19685673e+03
 8.68511374e+03 1.04811313e+04 1.26485522e+04 1.52641797e+04
 1.84206997e+04 2.22299648e+04 2.68269580e+04 3.23745754e+04
 3.90693994e+04 4.71486636e+04 5.68986603e+04 6.86648845e+04
 8.28642773e+04 1.00000000e+05]


# reshape()

In [8]:
# Convert 1D array into 2D array
a1 = arange(1,13)
a2 = a1.reshape(2,6)
print(a2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
# Convert 1D array into 3D array
a3 = a1.reshape(2,3,2)
print(a3)
a3.ndim

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


3

In [10]:
# Create a 2D array in one command
a = arange(1,13).reshape(2,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel() 

In [11]:
a1 = a3.ravel()
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# transpose() 

In [12]:
a1 = arange(1,13).reshape(2,6)
a = a1.transpose()
print(a)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [13]:
a3.transpose()

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

# zeros() 

In [14]:
a = zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [16]:
a = zeros((3,2), dtype = int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [21]:
a = zeros((3,2), dtype = str)
print(a)

[['' '']
 ['' '']
 ['' '']]


In [22]:
a = zeros((3,2), dtype = bool)
print(a)

[[False False]
 [False False]
 [False False]]


# ones()

In [17]:
a = ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [19]:
a = ones((3,2), dtype = int)
print(a)

[[1 1]
 [1 1]
 [1 1]]


In [20]:
a = ones((3,2), dtype = bool)
print(a)

[[ True  True]
 [ True  True]
 [ True  True]]
