In [1]:
from numpy import*
arr = array([101,102,103,104,105])

In [2]:
for element in arr:
    print(arr)

[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105]


In [3]:
type(arr)

numpy.ndarray