# NumPy Array Slicing (:)

In [1]:
from numpy import *

In [2]:
n = array([[10, 20 ,30], [40, 50, 60], [70, 80, 90]])
print(n)
print(n[0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 20 30]


In [3]:
print(n[1])

[40 50 60]


In [4]:
print(n[2])

[70 80 90]


# Slicing (:)

In [5]:
print("slicing 0th row all columns")
print(n[0, :])

slicing 0th row all columns
[10 20 30]


In [6]:
print("slicing 1st row all columns")
print(n[1, :])

slicing 1st row all columns
[40 50 60]


In [7]:
print("slicing 2nd row all columns")
print(n[2, :])

slicing 2nd row all columns
[70 80 90]


In [8]:
print("slicing 0th column all rows")
print(n[:, 0])

slicing 0th column all rows
[10 40 70]


In [9]:
print("slicing 1st column all rows")
print(n[:, 1])

slicing 1st column all rows
[20 50 80]


In [10]:
print("slicing 2nd column all rows")
print(n[:, 2])

slicing 2nd column all rows
[30 60 90]


In [11]:
print(n[:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
n[::]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
n[:,:]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
# slicing specific element

In [15]:
print(n[0:0, 0:0])

[]


In [16]:
n[0:1, 0:1]

array([[10]])

In [17]:
print(n[0:1, 0:1])

[[10]]


In [18]:
print(n[1:2, 1:2])

[[50]]


In [19]:
print(n[1:3, 1:3])

[[50 60]
 [80 90]]


In [20]:
print(n[0:2, 0:2])

[[10 20]
 [40 50]]


In [21]:
print(n[2:3, 2:3])

[[90]]


In [22]:
print(n[1:2, 0:1])

[[40]]


In [23]:
print(n[1:3, 1:2])

[[50]
 [80]]


In [24]:
print(n[:2])

[[10 20 30]
 [40 50 60]]


In [29]:
print(n[1:2, 2:3])

[[60]]


In [41]:
print(n[2:3, 0:1])

[[70]]


In [62]:
print(n[2:3, 1:2])

[[80]]


In [55]:
print(n[0:1, 2:3])

[[30]]


In [57]:
a =  arange(1,101).reshape(10,10)
print(a)



[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [78]:
print(a[:, 1:3])

[[ 2  3]
 [12 13]
 [22 23]
 [32 33]
 [42 43]
 [52 53]
 [62 63]
 [72 73]
 [82 83]
 [92 93]]


In [79]:
print(a[1:5, 1:5])

[[12 13 14 15]
 [22 23 24 25]
 [32 33 34 35]
 [42 43 44 45]]


In [80]:
a.itemsize

8

In [81]:
a.dtype

dtype('int64')